In [ ]:
# Retail Sales Analytics using Python & Tableau

## Objective
Analyze the Sample Superstore dataset using Python and build an interactive Tableau dashboard.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

print("Libraries imported successfully!")

Libraries imported successfully!

In [10]:
import pandas as pd

df = pd.read_excel(r"C:\Users\Laptop1\Desktop\Pallavi docs\Projects\data\raw\sample_-_superstore.xls")

In [11]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [12]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 10194
Columns : 21

In [13]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='str')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  datetime64[us]
 3   Ship Date       10194 non-null  datetime64[us]
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  str
 6   Customer Name   10194 non-null  str
 7   Segment         10194 non-null  str
 8   Country/Region  10194 non-null  str
 9   City            10194 non-null  str
 10  State/Province  10194 non-null  str
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  str
 13  Product ID      10194 non-null  str
 14  Category        10194 non-null  str
 15  Sub-Category    10194 non-null  str
 16  Product Name    10194 non-null  str
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[us](2), float64(3), int64(2), object(1), str(13)
memory usage: 1.6+ MB

In [15]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [16]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [17]:
df.describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-04-29 11:48:25.002943,2025-05-03 10:52:45.626839,228.225854,3.791838,0.155385,28.673417
min,1.000000,2023-01-03 00:00:00,2023-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,2024-05-14 00:00:00,2024-05-19 00:00:00,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,2025-06-25 00:00:00,2025-06-28 00:00:00,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,2026-05-14 00:00:00,2026-05-18 00:00:00,209.500000,5.000000,0.200000,29.297925
max,10194.000000,2026-12-30 00:00:00,2027-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [18]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

print("Date columns converted successfully!")

Date columns converted successfully!

In [19]:
print("Order Date Range")

print(df["Order Date"].min())

print(df["Order Date"].max())

Order Date Range
2023-01-03 00:00:00
2026-12-30 00:00:00

In [20]:
df["Order Year"] = df["Order Date"].dt.year

df["Order Month"] = df["Order Date"].dt.month_name()

df["Order Quarter"] = df["Order Date"].dt.quarter

df["Processing Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

df["Profit Margin (%)"] = (
    df["Profit"] / df["Sales"]
) * 100

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Order Quarter,Processing Days,Profit Margin (%)
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2023,January,1,4,33.75
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,2023,January,1,4,-155.00
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,2023,January,1,4,36.25
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,2023,January,1,4,-23.75
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2023,January,1,7,25.00

In [21]:
print("Total Sales")

print(round(df["Sales"].sum(),2))

Total Sales
2326534.35

In [22]:
print("Total Profit")

print(round(df["Profit"].sum(),2))

Total Profit
292296.81

In [23]:
print("Total Orders")

print(df["Order ID"].nunique())

Total Orders
5111

In [25]:
print("Sales by Region")
sales_region = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

sales_region

Sales by Region

Region
West       739813.6085
East       691828.1680
Central    503170.6728
South      391721.9050
Name: Sales, dtype: float64

In [26]:
print("Profit by Region")
profit_region = df.groupby("Region")["Profit"].sum().sort_values(ascending=False)

profit_region

Profit by Region

Region
West       110798.8170
East        94883.2603
South       46749.4303
Central     39865.3070
Name: Profit, dtype: float64

In [27]:
print("Sales by Category")
category_sales = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

category_sales

Sales by Category

Category
Technology         839893.2790
Furniture          754747.7613
Office Supplies    731893.3140
Name: Sales, dtype: float64

In [28]:
print("Profit by Category")
category_profit = df.groupby("Category")["Profit"].sum().sort_values(ascending=False)

category_profit

Profit by Category

Category
Technology         146543.3756
Office Supplies    126023.4434
Furniture           19729.9956
Name: Profit, dtype: float64

In [29]:
print("Sales by Segment")
segment_sales = df.groupby("Segment")["Sales"].sum().sort_values(ascending=False)

segment_sales

Sales by Segment

Segment
Consumer       1.170660e+06
Corporate      7.158061e+05
Home Office    4.400684e+05
Name: Sales, dtype: float64

In [30]:
print("Top 10 Customers")
top_customers = df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(10)

top_customers

Top 10 Customers

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

In [31]:
print("Top 10 Products")
top_products = df.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).head(10)

top_products

Top 10 Products

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [32]:
print("Monthly Sales Trend")
monthly_sales = df.groupby("Order Month")["Sales"].sum()

monthly_sales

Monthly Sales Trend

Order Month
April        138098.7486
August       161821.9150
December     330218.1755
February      59751.2514
January       96069.5156
July         149001.7130
June         153459.9973
March        210672.0868
May          158765.0337
November     352665.9910
October      207126.2567
September    308883.6697
Name: Sales, dtype: float64

In [34]:
print("State-wise Sales")
state_sales = df.groupby("State/Province")["Sales"].sum().sort_values(ascending=False)

state_sales.head(10)

State-wise Sales

State/Province
California      457687.6315
New York        310876.2710
Texas           170188.0458
Washington      138641.2700
Pennsylvania    116511.9140
Florida          89473.7080
Illinois         80166.1010
Ohio             78258.1360
Michigan         76269.6140
Virginia         70636.7200
Name: Sales, dtype: float64

In [35]:
print("Ship Mode Analysis")
ship_mode = df.groupby("Ship Mode")["Sales"].sum()

ship_mode

Ship Mode Analysis

Ship Mode
First Class       3.517507e+05
Same Day          1.292720e+05
Second Class      4.666711e+05
Standard Class    1.378841e+06
Name: Sales, dtype: float64

In [36]:
print("Discount Analysis")
discount = df.groupby("Discount")["Profit"].mean()

discount

Discount Analysis

Discount
0.00     66.338799
0.10     94.791354
0.15     27.288298
0.20     24.576350
0.30    -45.710633
0.32    -88.560656
0.40   -111.528378
0.45   -226.646464
0.50   -310.703456
0.60    -41.371458
0.70    -95.048521
0.80   -101.545745
Name: Profit, dtype: float64

In [37]:
print("Correlation")
df[["Sales","Profit","Quantity","Discount"]].corr()

Correlation

             Sales    Profit  Quantity  Discount
Sales     1.000000  0.481460  0.198457 -0.027756
Profit    0.481460  1.000000  0.066145 -0.218882
Quantity  0.198457  0.066145  1.000000  0.007475
Discount -0.027756 -0.218882  0.007475  1.000000

In [40]:
df.to_csv(r"C:\Users\Laptop1\Desktop\Pallavi docs\Projects\data\Superstore_Cleaned.csv",index=False)

print("Dataset exported successfully!")

Dataset exported successfully!

In [41]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Order Quarter,Processing Days,Profit Margin (%)
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2023,January,1,4,33.75
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,2023,January,1,4,-155.00
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,2023,January,1,4,36.25
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,2023,January,1,4,-23.75
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2023,January,1,7,25.00